# GitHub Actions workflow to run tests on Solaris.
# This action works by running a Solaris VM on macOS 12.
name: "Solaris"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 weekly on Sunday.

jobs:
  test:
    name: "Solaris 11.4"
    runs-on: "macos-12"
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install required packages"
        run: brew install automake autoconf libtool

      # The vmactions/solaris-vm action does not appear to work on VirtualBox 7.
      - name: "Install VirtualBox 6"
        run: |
          brew tap homebrew/cask-versions
          brew install --cask virtualbox6
          brew link virtualbox6

      - name: "Run autogen"
        run: ./autogen.sh

      - name: "Build on VM"
        uses: vmactions/solaris-vm@v0
        with:
          prepare: |
            pkg install gcc make
          run: |
            MAKE=gmake ./configure
            gmake -j2 check || (cat tests/test-suite.log && exit 1)
